//
// Created by 魏文俊 on 2022/7/3.
//

#ifndef CPPTHINGS_DESGIN_PATTERNS_BEHAVIOR_TEMPLATE_METHOD_H_
#define CPPTHINGS_DESGIN_PATTERNS_BEHAVIOR_TEMPLATE_METHOD_H_

#endif //CPPTHINGS_DESGIN_PATTERNS_BEHAVIOR_TEMPLATE_METHOD_H_
